# Generated by Django 6.1.1 on 2026-09-22 11:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('delivery', 'Delivery & Transport'), ('tutoring', 'Tutoring & Education'), ('events', 'Events & Catering'), ('trades', 'Plumbing, Electrical & Trades'), ('cleaning', 'Cleaning & Maintenance'), ('it', 'IT & Digital'), ('creative', 'Design, Photo & Video'), ('agriculture', 'Farming & Agriculture'), ('retail', 'Retail & Sales'), ('other', 'Other')], default='other', max_length=50)),
                ('description', models.TextField()),
                ('location', models.CharField(choices=[('gaborone', 'Gaborone'), ('francistown', 'Francistown'), ('maun', 'Maun'), ('serowe', 'Serowe'), ('selibe_phikwe', 'Selibe Phikwe'), ('orapa', 'Orapa'), ('kanye', 'Kanye'), ('molepolole', 'Molepolole'), ('kweneng', 'Kweneng'), ('lobatse', 'Lobatse'), ('remote', 'Remote'), ('other', 'Other')], default='gaborone', max_length=50)),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('budget_currency', models.CharField(default='BWP', max_length=3)),
                ('deadline', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('is_featured', models.BooleanField(default=False)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gigs_posted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GigApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('message', models.TextField()),
                ('quote_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('gig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gig_applications', to='jobs.gig')),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('featured_job', 'Featured Job Post'), ('featured_gig', 'Featured Gig Post'), ('subscription', 'Employer Subscription'), ('resume_spotlight', 'Resume Spotlight')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='BWP', max_length=3)),
                ('method', models.CharField(blank=True, help_text='e.g. MyZaka, Orange Money', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('refunded', 'Refunded')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
